version: "3.7"
   
services:

  backend:
    expose:
      - 80
    env_file:
      - ./env/.env.prod
    restart: always
    
  db:
    env_file:
      - ./env/.env.prod
    restart: always
    
  nginx_ssl:
    build: ./nginx_ssl
    ports:
      - "${NGINX_PORT:-443}:443"
      - "${NGINX_PORT:-80}:80"
    depends_on: 
      - backend

  nginx:
    env_file:
      - ./env/.env.prod
    restart: always

  frontend:
    env_file:
      - ./env/.env.prod
    restart: always
