version: "3.7"
   
services:

  backend:
    env_file:
      - ./env/.env.prod
    restart: always
    
  db:
    env_file:
      - ./env/.env.prod
    restart: always
    
  nginx:
    env_file:
      - ./env/.env.prod
    ports:
      - "${NGINX_PORT:-80}:80"  
    restart: always

  frontend:
    env_file:
      - ./env/.env.prod
    restart: always
