version: "3.7"
   
services:

  backend:
    build:
      context: ./inventory_backend/django
      target: deployment
    volumes:
      - static_volume:/home/dpdadm/web/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql

  nginx:
    build: ./nginx
    depends_on: 
      - backend
    volumes:
      - static_volume:/home/dpdadm/web/staticfiles

  frontend:
    build:
      context: ./map-frontend
      target: deployment
    volumes:
      - ./map-frontend:/usr/src/app
    expose:
      - 80
    depends_on:
      - backend

  translator:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./env/.env.dev
    environment:
      - LT_LOAD_ONLY=en,pt,es,ko,de
      - LT_THREADS=4
      - LT_CHAR_LIMIT=5000
    volumes:
      - lt_models:/home/libretranslate/.local 

volumes:
    postgres_data:
    static_volume:
    lt_models: