"""
Django settings for inventory_backend project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get('DEBUG') or 0)

# ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', default='').split(' ')

ALLOWED_HOSTS = []

ROOT_URLCONF = 'inventory_backend.urls'
TENANT_URLCONF = 'clients.urls'

# Multi-tenant settings
TENANT_MODEL = "clients.Client"
TENANT_DOMAIN_MODEL = "clients.Domain"
TENANT_USERS_DOMAIN = "localhost"
AUTH_USER_MODEL= "clients.TenantUser"

# Application definition
SHARED_APPS = [
    # Multi tenancy
    'django_tenants',
    'tenant_users.permissions',
    'tenant_users.tenants',
    'clients',
    # Apps
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Other Dependencies
    'colorfield',
    'rest_framework',
    'corsheaders',
    'tinymce',
    'axes',
]

TENANT_APPS = [
    'administration.apps.AdministrationConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'tenant_users.permissions',
]

HAS_MULTI_TYPE_TENANTS = True
MULTI_TYPE_DATABASE_FIELD = 'tenancytype'  # or whatever the name you call the database field

TENANT_TYPES = {
    "public": {
        "APPS": [
            'django_tenants',
            'tenant_users.permissions',
            'tenant_users.tenants',
            'clients',
            'axes',
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'colorfield',
            'rest_framework',
            'corsheaders',
            'tinymce',
        ],
        "URLCONF": ROOT_URLCONF,
    },
    "root": {
        "APPS": [
            'django_tenants',
            'tenant_users.permissions',
            'tenant_users.tenants',
            'axes',
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'colorfield',
            'rest_framework',
            'corsheaders',
            'tinymce',
        ],
        "URLCONF": ROOT_URLCONF,
    },
    "scoped": {
        "APPS": [
            'administration.apps.AdministrationConfig',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'tenant_users.permissions',
        ],
        "URLCONF": TENANT_URLCONF,
    }
}

INSTALLED_APPS = []
for schema in TENANT_TYPES:
    INSTALLED_APPS += [app for app in TENANT_TYPES[schema]["APPS"] if app not in INSTALLED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

# Axes config (suspicious login middleware)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_FAIL_RETRY_LIMIT = 5
AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]]
AXES_CACHE = 'default'
AXES_ENABLE_ADMIN = True
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'tenant_users.permissions.backend.UserBackend',
]

CORS_ORIGIN_WHITELIST = (
    os.environ.get('CORS_WHITELIST'),
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'my_templatetag': 'administration.templatetags.importer_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'inventory_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": 'django_tenants.postgresql_backend',
        "HOST": 'db',
        "PORT": 5432,
        "NAME": os.environ.get("POSTGRES_DB", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("POSTGRES_USER", "user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# STATIC_URL = '/static/'
STATIC_URL = '/staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "skin": "oxide-dark",
    "height": 300,
    "menubar": True,
    "plugins": "advlist,autolink,code,lists,link,image,charmap,print,preview,anchor,"
    "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
    "code,help,wordcount",
    "toolbar": "code | undo redo | formatselect | fontsizeselect | forecolor | link image |"
    "bold italic backcolor | alignleft aligncenter "
    "alignright alignjustify | outdent indent | "
    "removeformat | help",
}
