# Generated by Django 3.2.5 on 2021-07-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='related_tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='related_locations',
            field=models.ManyToManyField(to='administration.Location'),
        ),
    ]
