# Generated by Django 3.2.5 on 2021-07-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210716_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='parent_menu_id',
            new_name='parent_menu',
        ),
        migrations.AlterField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Tag_relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.IntegerField()),
                ('is_subtag', models.BooleanField(default=False)),
                ('parent_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_tag', to='administration.tag')),
                ('primary_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tag', to='administration.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='related_tags',
            field=models.ManyToManyField(blank=True, through='administration.Tag_relationship', to='administration.Tag'),
        ),
    ]
