# Generated by Django 3.2.5 on 2021-07-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20210716_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag_relationship',
            options={'ordering': ['primary_tag']},
        ),
        migrations.AlterModelTable(
            name='tag_relationship',
            table='tag_relationship',
        ),
    ]
