# Generated by Django 3.2.5 on 2021-07-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_tag_relationship_path_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['hierarchy_level']},
        ),
        migrations.AlterModelOptions(
            name='tag_relationship',
            options={'ordering': ['child_tag']},
        ),
        migrations.RenameField(
            model_name='tag_relationship',
            old_name='primary_tag',
            new_name='child_tag',
        ),
    ]
