# Generated by Django 3.2.5 on 2021-07-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_relationship',
            name='child_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tag', to='administration.tag'),
        ),
    ]
