# Generated by Django 3.2.8 on 2021-10-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_tag_relationship_child_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=django.db.models.deletion.SET_NULL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='related_locations',
            field=models.ManyToManyField(blank=True, to='administration.Location'),
        ),
        migrations.AlterField(
            model_name='tag_relationship',
            name='child_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tag', to='administration.tag'),
        ),
        migrations.AlterField(
            model_name='tag_relationship',
            name='parent_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_tag', to='administration.tag'),
        ),
    ]
