# Generated by Django 3.2.9 on 2021-11-12 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20211014_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=25)),
                ('map_style', models.CharField(choices=[('d', 'Default (gray colored)'), ('b', 'Blue colored')], default='Default (gray colored)', max_length=15)),
                ('inherit_children_tag_locations', models.BooleanField(default=False)),
                ('initial_zoom_level', models.PositiveIntegerField(default=0, help_text='Please insert a value from 0 to 13.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)])),
                ('initial_latitude', models.DecimalField(decimal_places=20, default=0.0, max_digits=24)),
                ('initial_longitude', models.DecimalField(decimal_places=20, default=0.0, max_digits=24)),
            ],
            options={
                'verbose_name': 'Map Configuration',
                'verbose_name_plural': 'Map Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name_plural': '   Locations'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['hierarchy_level'], 'verbose_name_plural': '    Menus'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name_plural': '  Tags'},
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=24),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=24),
        ),
    ]
