# Generated by Django 3.2.9 on 2021-11-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20211112_1905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='map_configuration',
            table='map_config',
        ),
    ]
