# Generated by Django 3.2.9 on 2021-11-13 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_map_configuration_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map_configuration',
            options={'verbose_name': 'Map Settings', 'verbose_name_plural': 'Map Settings'},
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='inherit_children_tag_locations',
            field=models.BooleanField(default=False, help_text='When this field is enabled, a tag that is parent from another tags will inherit all locations from the children that was not previously declared on the parent. If instead you want to manually declare the locations for all tags, we suggest to keep this field disabled.'),
        ),
        migrations.AlterField(
            model_name='map_configuration',
            name='initial_zoom_level',
            field=models.PositiveIntegerField(default=0, help_text='Please insert a value from 0 to 13 (max zoom).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
