# Generated by Django 3.2.9 on 2021-11-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20211123_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_configuration',
            name='cluster_close_tags',
            field=models.BooleanField(default=True, help_text='When this field is enabled, tags located very close to each other will be grouped in clusters.'),
        ),
    ]
