# Generated by Django 3.2.9 on 2021-12-02 21:47

from django.db import models, migrations

def defaultSettings(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Config = apps.get_model("administration", "Map_configuration")
    config = Config(
        id = 0, 
        map_name = "Default Map", 
        map_style = "d", 
        inherit_children_tag_locations = False,
        cluster_close_tags = True,
        initial_zoom_level = "0",
        initial_latitude = 14.57950740769544000,
        initial_longitude = -55.92525392265914000
    )
    config.save()

class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_map_configuration_cluster_close_tags'),
    ]

    operations = [
        migrations.RunPython(defaultSettings),
    ]
