# Generated by Django 3.2.11 on 2022-01-31 14:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_auto_20211202_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag_relationship',
            options={'ordering': ['child_tag'], 'verbose_name': 'Tag to tag relation', 'verbose_name_plural': 'Tag to tag relationships'},
        ),
        migrations.RemoveField(
            model_name='tag_relationship',
            name='is_subtag',
        ),
        migrations.RemoveField(
            model_name='tag_relationship',
            name='path_id',
        ),
        migrations.AddField(
            model_name='tag_relationship',
            name='cluster_id',
            field=models.IntegerField(blank=django.db.models.deletion.SET_NULL, default=1, help_text='Tag clusters are group of parent tags from the tag. To a cluster id be active, all tags in that id must be active. The child tag will be active if at least one of the cluster ids is active.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='hierarchy_level',
            field=models.IntegerField(default=0, help_text='Menus with the same number are considered siblings. Menus with lower numbers are considered parents of the ones with higher numbers. For example, a menu with the number 0 is considered parent of menus with the number 1.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, null=True),
        ),
    ]
