# Generated by Django 3.2.11 on 2022-02-01 19:08

from django.db import migrations
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_auto_20220131_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sidebar_content',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, help_text="<b style='font-size: 0.85rem'>* Leave blank to use default template</b>", null=True),
        ),
    ]
