# Generated by Django 3.2.15 on 2022-10-07 13:55

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_tag_sidebar_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('links_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('sidebar_content', tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, null=True)),
            ],
            options={
                'verbose_name': 'Links group',
                'verbose_name_plural': 'Links groups',
                'db_table': 'links_group',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, null=True, verbose_name='Popup content'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=25)),
                ('popup_description', tinymce.models.HTMLField(blank=django.db.models.deletion.SET_NULL, null=True)),
                ('links_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.links_group')),
                ('location_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_1', to='administration.location')),
                ('location_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_2', to='administration.location')),
            ],
            options={
                'db_table': 'link',
            },
        ),
    ]
