# Generated by Django 3.2.20 on 2024-07-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_map_configuration_footer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_configuration',
            name='footer_file',
            field=models.ImageField(blank=True, help_text='Upload a custom footer file.', upload_to='uploads/'),
        ),
    ]
