# Generated by Django 3.2.25 on 2024-09-21 14:29

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_alter_map_configuration_footer_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='KML_link_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('links_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('opacity', models.DecimalField(decimal_places=3, default=0.6, help_text='Opacity of the link. Min(0)-Max(1)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('kml_file', models.FileField(help_text='Upload a custom KML file (max 30Mb).', upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['kml'])])),
            ],
            options={
                'verbose_name': 'KML Links group',
                'verbose_name_plural': 'KML Links groups',
                'db_table': 'kml_links_group',
                'ordering': ['name'],
            },
        ),
    ]
