# Generated by Django 3.2.25 on 2024-10-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_auto_20241009_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kml_shape',
            options={'ordering': ['name'], 'verbose_name': 'KML Shape', 'verbose_name_plural': 'KML Shapes'},
        ),
        migrations.AddField(
            model_name='links_group',
            name='parent_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.menu'),
        ),
    ]
