# Generated by Django 3.2.25 on 2024-10-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_auto_20241016_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='dashed',
            field=models.BooleanField(default=False, help_text='This field, when active, will make the link stroke dashed.'),
        ),
        migrations.AddField(
            model_name='link',
            name='straight_link',
            field=models.BooleanField(default=False, help_text='This field, when active, will make the link line straight.'),
        ),
        migrations.AddField(
            model_name='link',
            name='weight',
            field=models.IntegerField(default=3, help_text='This field controls the weight of the link line. The higher the number, the wider the line.', null=True),
        ),
    ]
