# Generated by Django 3.2.25 on 2025-04-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0029_menugroup_simultaneous_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_configuration',
            name='hide_menu_group_when_unique',
            field=models.BooleanField(default=True, help_text='When there is only one Menu Group active, hide the menu groups tabs'),
        ),
    ]
