
class StringConstraints:
    DEFAULT_TITLE_NAMES_CHAR_NUMBER = 2000
    MENU_NAME_MAX_CHAR_NUMBER = DEFAULT_TITLE_NAMES_CHAR_NUMBER
    TAG_NAME_MAX_CHAR_NUMBER = DEFAULT_TITLE_NAMES_CHAR_NUMBER

    LANGUAGE_CODE_MAX_CHAR_NUMBER = 20